# Generated by Django 3.0.8 on 2020-07-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name_med', models.CharField(max_length=200)),
                ('dosis_name_med', models.CharField(max_length=30)),
                ('init_date_med', models.DateField()),
                ('end_date_med', models.DateField()),
                ('time_med', models.DateTimeField()),
            ],
        ),
    ]
