# Generated by Django 3.0.8 on 2020-08-02 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservaccine',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserDiet',
        ),
        migrations.DeleteModel(
            name='UserVaccine',
        ),
    ]
