# Generated by Django 3.0.8 on 2020-07-29 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server_app', '0003_auto_20200728_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
