# Generated by Django 3.0.8 on 2020-07-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0005_auto_20200717_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_include', models.TextField(max_length=500)),
            ],
        ),
    ]
