# Generated by Django 3.0.8 on 2020-08-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0007_auto_20200806_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrip',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
