# Generated by Django 3.0.7 on 2020-08-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0010_auto_20200811_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiet',
            name='meal',
            field=models.CharField(choices=[(1, 'Café'), (2, 'Almoço'), (3, 'Jantar'), (4, 'Lanche')], default=None, max_length=1, null=True),
        ),
    ]
