# Generated by Django 3.0.7 on 2020-08-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0016_auto_20200815_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiet',
            name='meal',
            field=models.CharField(choices=[('Café', 'Café'), ('Almoço', 'Almoço'), ('Jantar', 'Jantar'), ('Snacks', 'Snacks')], default=None, max_length=10),
        ),
    ]
