# Generated by Django 3.0.7 on 2020-08-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0017_auto_20200815_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiet',
            name='meal',
            field=models.CharField(choices=[('cafe', 'Café'), ('almoco', 'Almoço'), ('jantar', 'Jantar'), ('snacks', 'Snacks')], default=None, max_length=10),
        ),
    ]
