# Generated by Django 3.0.7 on 2020-08-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0021_remove_userprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
