# Generated by Django 3.0.8 on 2020-08-21 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server_app', '0022_userprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoint_espec_apt', models.CharField(max_length=50)),
                ('appoint_date_apt', models.DateField()),
                ('appoint_time_apt', models.TimeField()),
                ('appoint_nmed_apt', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='slug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
