# Generated by Django 3.0.8 on 2020-08-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0024_userappoint_appoint_credenc_apt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiet',
            name='meal',
            field=models.CharField(choices=[('Café', 'Café'), ('Almoço', 'Almoço'), ('Jantar', 'Jantar'), ('Snacks', 'Snacks')], default=None, max_length=10),
        ),
    ]
