# Generated by Django 3.0.8 on 2020-08-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0025_auto_20200826_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiet',
            name='meal',
            field=models.CharField(choices=[('Cafe', 'Café'), ('Almoco', 'Almoço'), ('Jantar', 'Jantar'), ('Snacks', 'Snacks')], default=None, max_length=10),
        ),
    ]
