# Generated by Django 3.0.8 on 2020-08-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0026_auto_20200826_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiet',
            name='meal',
            field=models.CharField(choices=[('Café', 'Café'), ('Almoço', 'Almoço'), ('Jantar', 'Jantar'), ('Snacks', 'Snacks')], default=None, max_length=10),
        ),
    ]
