# Generated by Django 3.0.7 on 2020-09-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0027_auto_20200826_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_blood_prf',
            field=models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], default=None, max_length=10, null=True),
        ),
    ]
