# Generated by Django 3.0.7 on 2020-09-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0028_userprofile_profile_blood_prf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_age_prf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_allergy_prf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_blood_prf',
            field=models.CharField(blank=True, choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_desease_prf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_diet_prf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_exerc_prf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_height_prf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_loc_prf',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_surgery_prf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_weight_prf',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
