# Generated by Django 3.0.7 on 2020-09-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0029_auto_20200918_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiet',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
