# Generated by Django 3.0.7 on 2020-09-23 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0030_userdiet_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdiet',
            name='picture',
        ),
    ]
